"""cs789rag.py -- the fixed evaluation harness for CS 789 Assignments 4 and 5.

Everything that must be IDENTICAL for every student lives here, so that two students'
numbers can be compared: the corpus loader, the question set, the metrics, the results
log, the plots, and the helpers that start and stop the local LLM server.

Everything you BUILD (chunkers, retrievers, vector-store pipelines, RAG prompts) lives in
your notebook and is written with your AI assistant. Do not edit this file -- if your
numbers depend on a modified harness they are not comparable with anyone else's.

Quick reference
---------------
    import cs789rag as H
    docs = H.load_corpus()                 # 35 Document objects (doc_id, title, text, ...)
    Q    = H.load_questions()              # 26 question dicts (id, question, type, gold_*)

    H.check_chunker(my_fixed_chunker)      # contract test for a chunker you wrote
    H.eval_retrieval("A-chunking", {"chunker": "fixed", "size": 800}, retrieve_fn, k=5)
    H.eval_answers("E-answers", {"pipeline": "naive"}, answer_fn)
    H.table("A-chunking")                  # pivot: config x question type
    H.plot_sweep("A-chunking", x="size", series="chunker")

A retrieve_fn is ``retrieve_fn(question: str, k: int) -> list``; each element is a
doc_id string, or a dict/object that has a ``doc_id`` (a chunk). Return chunks best-first.
An answer_fn is ``answer_fn(question: str) -> str``.
"""

from __future__ import annotations

import json
import math
import os
import re
import subprocess
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Iterable, Sequence

import yaml

HERE = Path(__file__).resolve().parent
CORPUS_DIR = HERE / "corpus"
QUESTIONS_FILE = HERE / "questions.yaml"
RESULTS_DIR = HERE / "results"
TYPES = ["single_hop", "multi_hop", "aggregation", "temporal", "negation", "lexical"]
FACT_THRESHOLD = 0.6          # fact coverage >= this counts as a correct answer

# =========================================================================== corpus

_FM_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n?", re.S)


@dataclass
class Document:
    doc_id: str
    title: str
    doc_type: str
    date: str
    status: str
    text: str                                   # body, front matter stripped
    path: str = ""
    front_matter: dict = field(default_factory=dict)

    def metadata(self) -> dict:
        """Flat str->str metadata, safe for every vector store."""
        return {"doc_id": self.doc_id, "title": self.title, "type": self.doc_type,
                "date": self.date, "status": self.status}


def load_corpus(corpus_dir: str | Path | None = None) -> list[Document]:
    """Load the 35 Vandelay Industries documents, sorted by doc_id."""
    d = Path(corpus_dir or CORPUS_DIR)
    docs = []
    for p in sorted(d.glob("*.md")):
        raw = p.read_text(encoding="utf-8")
        m = _FM_RE.match(raw)
        fm = yaml.safe_load(m.group(1)) if m else {}
        fm = {k: (v if isinstance(v, (list, dict)) else str(v)) for k, v in (fm or {}).items()}
        body = raw[m.end():] if m else raw
        docs.append(Document(doc_id=str(fm.get("id", p.stem)), title=str(fm.get("title", p.stem)),
                             doc_type=str(fm.get("type", "")), date=str(fm.get("date", "")),
                             status=str(fm.get("status", "current")), text=body.strip(),
                             path=str(p), front_matter=fm))
    ids = [x.doc_id for x in docs]
    assert len(ids) == len(set(ids)), "duplicate doc ids in corpus"
    return sorted(docs, key=lambda x: x.doc_id)


def load_questions(path: str | Path | None = None) -> list[dict]:
    """Load the 26 evaluation questions."""
    data = yaml.safe_load(Path(path or QUESTIONS_FILE).read_text(encoding="utf-8"))
    out = []
    for q in data["questions"]:
        out.append({
            "id": str(q["id"]),
            "question": " ".join(str(q["question"]).split()),
            "type": str(q["type"]),
            "hops": int(q.get("hops", 1)),
            "gold_answer": " ".join(str(q.get("gold_answer", "")).split()),
            "gold_facts": [str(f) for f in (q.get("gold_facts") or [])],
            "gold_doc_ids": [str(x) for x in (q.get("gold_doc_ids") or [])],
        })
    return out


def corpus_text(docs: Sequence[Document] | None = None, with_headers: bool = True) -> str:
    """The whole corpus as one string (used for the full-context baseline)."""
    docs = docs or load_corpus()
    parts = []
    for d in docs:
        head = f"### [{d.doc_id}] {d.title} ({d.date}, status: {d.status})\n" if with_headers else ""
        parts.append(head + d.text)
    return "\n\n".join(parts)


# ========================================================================== metrics

_NORM = re.compile(r"[^a-z0-9]+")
_TOK = re.compile(r"[a-z0-9]+")
ABSTAIN = ("i do not know", "i don't know", "do not know", "not in the corpus", "not stated",
           "not mentioned", "not specified", "not present in", "no information",
           "does not contain", "cannot be determined", "cannot determine", "is not available",
           "no evidence", "the corpus does not", "the context does not",
           "the documents do not", "insufficient information", "unable to answer",
           "no mention of", "none of the retrieved", "nothing in the provided", "unanswerable",
           "not found in", "no record", "there is no", "not have enough information",
           "not enough information", "does not mention", "do not mention", "not provide")


def _norm(s: Any) -> str:
    return _NORM.sub(" ", str(s).lower()).strip()


def _toks(s: Any) -> list[str]:
    return _TOK.findall(str(s).lower())


def doc_ids_of(retrieved: Iterable) -> list[str]:
    """Turn whatever a retriever returned into a de-duplicated, ranked list of doc_ids."""
    out, seen = [], set()
    for r in retrieved or []:
        if isinstance(r, str):
            d = r.split("::")[0]
        elif isinstance(r, dict):
            d = r.get("doc_id") or (r.get("metadata") or {}).get("doc_id")
        elif isinstance(r, (tuple, list)) and r and isinstance(r[0], str):
            d = r[0].split("::")[0]
        else:  # LangChain Document, LlamaIndex NodeWithScore, anything with metadata
            meta = getattr(r, "metadata", None)
            if meta is None and hasattr(r, "node"):
                meta = getattr(r.node, "metadata", None)
            d = (meta or {}).get("doc_id") or getattr(r, "doc_id", None)
        if d and d not in seen:
            seen.add(d)
            out.append(str(d))
    return out


def recall_at(ranked_docs: Sequence[str], gold: Sequence[str], k: int | None = None) -> float:
    g = set(gold)
    if not g:
        return float("nan")
    top = set(ranked_docs if k is None else ranked_docs[:k])
    return len(g & top) / len(g)


def mrr(ranked_docs: Sequence[str], gold: Sequence[str]) -> float:
    g = set(gold)
    if not g:
        return float("nan")
    for i, d in enumerate(ranked_docs, 1):
        if d in g:
            return 1.0 / i
    return 0.0


def fact_present(fact: str, answer: str) -> bool:
    nf, na = _norm(fact), _norm(answer)
    if nf and nf in na:
        return True
    ft = _toks(fact)
    if len(ft) >= 3:
        at = set(_toks(answer))
        return sum(t in at for t in ft) / len(ft) >= 0.85
    return False


def abstained(answer: str) -> bool:
    na = _norm(answer)
    return any(_norm(m) in na for m in ABSTAIN)


def score_answer(q: dict, answer: str) -> dict:
    """Score one answer: fact coverage, correct, abstained, hallucinated.

    negation questions: correct only if the model abstains; a confident answer is H.
    other questions: coverage = fraction of gold_facts present; correct if >= 0.6.
    Grade letter (same scheme as A3): C correct, W wrong, H hallucinated, A abstained.
    """
    answer = answer or ""
    ab = abstained(answer)
    if q["type"] == "negation":
        cov = 1.0 if ab else 0.0
        correct = ab
        grade = "C" if ab else "H"
        found, missing = [], []
    else:
        found = [f for f in q["gold_facts"] if fact_present(f, answer)]
        missing = [f for f in q["gold_facts"] if f not in found]
        cov = len(found) / max(1, len(q["gold_facts"]))
        correct = cov >= FACT_THRESHOLD
        grade = "C" if correct else ("A" if ab else ("W" if cov > 0 else "H"))
    return {"coverage": round(cov, 3), "correct": bool(correct), "abstained": ab,
            "grade": grade, "found": found, "missing": missing}


# ====================================================================== results log

_LOG: list[dict] = []


def _save():
    RESULTS_DIR.mkdir(exist_ok=True)
    with open(RESULTS_DIR / "results.jsonl", "w") as f:
        for r in _LOG:
            f.write(json.dumps(r, default=str) + "\n")


def _load():
    p = RESULTS_DIR / "results.jsonl"
    if p.exists() and not _LOG:
        _LOG.extend(json.loads(l) for l in p.read_text().splitlines() if l.strip())


_load()


def _config_label(cfg: dict) -> str:
    return ", ".join(f"{k}={v}" for k, v in cfg.items())


def _record(experiment: str, cfg: dict, rows: list[dict], extra: dict):
    # replace an earlier run of the same experiment+config
    label = _config_label(cfg)
    _LOG[:] = [r for r in _LOG if not (r["experiment"] == experiment and r["config"] == label)]
    _LOG.append({"experiment": experiment, "config": label, "cfg": cfg, "rows": rows,
                 "extra": extra, "time": time.strftime("%Y-%m-%d %H:%M:%S")})
    _save()


def clear(experiment: str | None = None):
    """Forget recorded results (all, or one experiment)."""
    _LOG[:] = [r for r in _LOG if experiment and r["experiment"] != experiment]
    _save()


# ======================================================================= evaluators

def eval_retrieval(experiment: str, cfg: dict, retrieve: Callable[[str, int], list],
                   k: int = 5, questions: list[dict] | None = None, verbose: bool = True):
    """Run every non-negation question through ``retrieve(question, k)`` and score it.

    Metric: recall@k over DOCUMENTS -- the fraction of a question's gold documents that
    appear among the documents of the top-k chunks you returned. A multi-hop question
    with 4 gold documents needs all 4 in the top k to score 1.0.
    Returns a pandas DataFrame with one row per question.
    """
    import pandas as pd
    questions = [q for q in (questions or load_questions()) if q["gold_doc_ids"]]
    rows, t0 = [], time.time()
    for q in questions:
        t = time.time()
        got = retrieve(q["question"], k)
        dt = time.time() - t
        docs = doc_ids_of(got)
        rows.append({"id": q["id"], "type": q["type"], "recall": recall_at(docs, q["gold_doc_ids"]),
                     "mrr": mrr(docs, q["gold_doc_ids"]), "n_docs": len(docs),
                     "retrieved": docs[:10], "gold": q["gold_doc_ids"], "sec": round(dt, 4)})
    extra = {"k": k, "total_sec": round(time.time() - t0, 2)}
    _record(experiment, cfg, rows, extra)
    df = pd.DataFrame(rows)
    if verbose:
        by = df.groupby("type")["recall"].mean().reindex([t for t in TYPES if t != "negation"])
        print(f"[{experiment}] {_config_label(cfg)}  k={k}  "
              f"recall@{k}={df.recall.mean():.3f}  MRR={df.mrr.mean():.3f}  "
              f"({extra['total_sec']}s)")
        print("   " + "  ".join(f"{t[:9]}={v:.2f}" for t, v in by.items()))
    return df


def eval_answers(experiment: str, cfg: dict, answer: Callable[[str], Any],
                 questions: list[dict] | None = None, verbose: bool = True, show: bool = False):
    """Run every question through ``answer(question)`` and grade it against the gold facts.

    ``answer`` may return a string, or a (string, retrieved_chunks) tuple.
    Returns a pandas DataFrame with one row per question (grade C / W / H / A).
    """
    import pandas as pd
    questions = questions or load_questions()
    rows, t0 = [], time.time()
    for q in questions:
        t = time.time()
        out = answer(q["question"])
        dt = time.time() - t
        text, docs = (out[0], doc_ids_of(out[1])) if isinstance(out, tuple) else (str(out), [])
        s = score_answer(q, text)
        rows.append({"id": q["id"], "type": q["type"], **s, "answer": text.strip(),
                     "retrieved": docs[:10], "sec": round(dt, 2)})
        if show:
            print(f"--- {q['id']} [{s['grade']}] {q['question']}\n{text.strip()[:600]}\n")
    extra = {"total_sec": round(time.time() - t0, 1)}
    _record(experiment, cfg, rows, extra)
    df = pd.DataFrame(rows)
    if verbose:
        g = df.grade.value_counts().to_dict()
        print(f"[{experiment}] {_config_label(cfg)}  accuracy={df.correct.mean():.3f} "
              f"({int(df.correct.sum())}/{len(df)})  grades={g}  ({extra['total_sec']}s)")
    return df


def table(experiment: str, metric: str | None = None, by_type: bool = True):
    """Pivot of an experiment: one row per config, one column per question type."""
    import pandas as pd
    runs = [r for r in _LOG if r["experiment"] == experiment]
    if not runs:
        print(f"no results recorded for {experiment!r}")
        return None
    out = []
    for r in runs:
        df = pd.DataFrame(r["rows"])
        m = metric or ("recall" if "recall" in df else "correct")
        row = {"config": r["config"]}
        if by_type:
            for t in TYPES:
                sub = df[df.type == t]
                if len(sub):
                    row[t] = round(float(sub[m].mean()), 3)
        row["overall"] = round(float(df[m].mean()), 3)
        if "mrr" in df:
            row["MRR"] = round(float(df["mrr"].mean()), 3)
        if "grade" in df:
            row["H"] = int((df.grade == "H").sum())
            row["A"] = int((df.grade == "A").sum())
        row.update({k: v for k, v in r["extra"].items() if k not in ("k",)})
        out.append(row)
    return pd.DataFrame(out).set_index("config")


def rows(experiment: str, config_contains: str = ""):
    """Per-question rows of the runs of an experiment (optionally filtered by config)."""
    import pandas as pd
    frames = []
    for r in _LOG:
        if r["experiment"] == experiment and config_contains in r["config"]:
            df = pd.DataFrame(r["rows"])
            df.insert(0, "config", r["config"])
            frames.append(df)
    return pd.concat(frames, ignore_index=True) if frames else None


def plot_sweep(experiment: str, x: str, series: str | None = None, metric: str | None = None,
               title: str | None = None, logx: bool = False):
    """Line plot of overall metric vs. a numeric config key, one line per ``series`` value."""
    import matplotlib.pyplot as plt
    import pandas as pd
    pts = []
    for r in _LOG:
        if r["experiment"] != experiment or x not in r["cfg"]:
            continue
        df = pd.DataFrame(r["rows"])
        m = metric or ("recall" if "recall" in df else "correct")
        pts.append({"x": r["cfg"][x], "s": r["cfg"].get(series, "") if series else "", "y": df[m].mean()})
    if not pts:
        print("nothing to plot")
        return
    d = pd.DataFrame(pts).sort_values("x")
    fig, ax = plt.subplots(figsize=(7, 4))
    for s, g in d.groupby("s"):
        ax.plot(g.x, g.y, marker="o", label=str(s) if series else None)
    ax.set_xlabel(x)
    ax.set_ylabel(metric or "mean recall / accuracy")
    if logx:
        ax.set_xscale("log", base=2)
    ax.set_ylim(0, 1.02)
    ax.grid(alpha=.3)
    ax.set_title(title or experiment)
    if series:
        ax.legend(title=series)
    plt.tight_layout()
    plt.show()


def plot_bars(experiment: str, metric: str | None = None, title: str | None = None):
    """Grouped bar chart: question types on x, one bar per config."""
    import matplotlib.pyplot as plt
    t = table(experiment, metric)
    if t is None:
        return
    cols = [c for c in TYPES if c in t.columns] + ["overall"]
    ax = t[cols].T.plot(kind="bar", figsize=(max(7, 1.3 * len(cols)), 4), width=.8)
    ax.set_ylim(0, 1.05)
    ax.set_ylabel(metric or "recall@k / accuracy")
    ax.set_title(title or experiment)
    ax.legend(fontsize=8, loc="upper left", bbox_to_anchor=(1, 1))
    ax.grid(axis="y", alpha=.3)
    plt.xticks(rotation=20)
    plt.tight_layout()
    plt.show()


# ==================================================================== contract tests

def check_chunker(fn: Callable, name: str = "chunker") -> bool:
    """Contract test for ``fn(text, chunk_size, overlap) -> list[str]``.

    Checks: returns a list of strings; no chunk longer than chunk_size (+10% slack for
    splitters that measure differently); the chunks cover the text; overlap is honoured.
    """
    text = load_corpus()[0].text
    ok = True
    for size, ov in [(200, 0), (400, 40), (800, 100)]:
        ch = fn(text, size, ov)
        if not isinstance(ch, list) or not all(isinstance(c, str) for c in ch):
            print(f"  FAIL {name}({size},{ov}): must return list[str], got {type(ch)}")
            return False
        too_long = [len(c) for c in ch if len(c) > size * 1.1]
        compact = lambda s: re.sub(r"\s+", "", s)
        covered = len(compact("".join(ch))) >= 0.98 * len(compact(text))
        words = set(_toks(text))
        broken = [w for w in words if w not in set(_toks(" ".join(ch)))]
        cut = sum(1 for c in ch if _toks(c) and (_toks(c)[-1] not in words or _toks(c)[0] not in words))
        print(f"  {name}(size={size}, overlap={ov}): {len(ch)} chunks, "
              f"max len {max(map(len, ch))}, min len {min(map(len, ch))}, "
              f"chunks that start or end mid-word: {cut}, words cut in half (and lost as tokens): {len(broken)}")
        if too_long:
            print(f"  FAIL: {len(too_long)} chunks longer than {size}")
            ok = False
        if not covered:
            print("  FAIL: the chunks do not cover the whole text -- something was dropped")
            ok = False
    print("PASS" if ok else "FIX THE CHUNKER BEFORE CONTINUING")
    return None if ok else False    # None: nothing extra is displayed when the check passes


def check_retriever(fn: Callable, name: str = "retriever") -> bool:
    """Contract test for ``fn(question, k) -> ranked list of chunks/doc_ids``."""
    q = "Who is the primary owner of the workstation VAN-WKS-4471?"
    got = fn(q, 5)
    docs = doc_ids_of(got)
    ok = isinstance(got, list) and 0 < len(got) <= 5 and len(docs) > 0
    print(f"  {name}: returned {len(got)} items -> docs {docs}")
    print("PASS" if ok else "FAIL: must return a list of up to k chunks that carry a doc_id")
    return None if ok else False    # None: nothing extra is displayed when the check passes


# ================================================================== LLM server (vLLM)

_ON_COLAB = Path("/content").is_dir()
VLLM_ENV = os.environ.get("CS789_VLLM_ENV") or ("/content/vllm-env" if _ON_COLAB else str(HERE / "vllm-env"))
VLLM_LOG = "/content/vllm.log" if _ON_COLAB else str(HERE / "vllm.log")
VLLM_PORT = 8000
DEFAULT_MODEL = "Qwen/Qwen3-4B-Instruct-2507"


def install_vllm(env: str = VLLM_ENV):
    """Install vLLM into its OWN virtualenv so it cannot break the notebook's torch."""
    if Path(env, "bin", "vllm").exists():
        print("vLLM already installed in", env)
        return
    t = time.time()
    subprocess.run(f"CS789_VLLM_ENV={env} bash {HERE / 'install_vllm.sh'}", shell=True, check=True)
    print(f"vLLM installed in {time.time() - t:.0f}s")


_PROCS: dict = {}          # port -> subprocess.Popen


def _log_path(port: int) -> str:
    return VLLM_LOG.replace(".log", f"_{port}.log")


def _start_server(cmd: str, port: int, timeout: int, what: str):
    stop_vllm(port)
    log = open(_log_path(port), "w")
    t = time.time()
    env = dict(os.environ)
    # the venv's bin must come first: FlashInfer JIT-compiles kernels with the venv's `ninja`
    env["PATH"] = f"{VLLM_ENV}/bin:/usr/local/cuda/bin:" + env.get("PATH", "")
    env["VIRTUAL_ENV"] = VLLM_ENV
    proc = subprocess.Popen(cmd, shell=True, stdout=log, stderr=subprocess.STDOUT, preexec_fn=os.setsid,
                            env=env)
    _PROCS[port] = proc
    import requests
    while time.time() - t < timeout:
        if proc.poll() is not None:
            print(Path(_log_path(port)).read_text()[-3000:])
            raise RuntimeError(f"vLLM ({what}) exited while starting -- see the log above")
        try:
            if requests.get(f"http://localhost:{port}/v1/models", timeout=2).ok:
                return round(time.time() - t)
        except Exception:
            pass
        time.sleep(5)
    raise TimeoutError(f"vLLM ({what}) did not come up; see {_log_path(port)}")


def start_vllm(kv_cache_dtype: str = "auto", model: str = DEFAULT_MODEL,
               max_model_len: int = 49152, gpu_mem: float = 0.85, port: int = VLLM_PORT,
               extra: str = "", timeout: int = 1500) -> dict:
    """(Re)start the vLLM chat server (OpenAI API on localhost:port, model name "llm").

    kv_cache_dtype: auto (bf16), fp8, turboquant_k8v4, turboquant_4bit_nc,
                    turboquant_k3v4_nc, turboquant_3bit_nc
    Returns {"kv_cache_dtype", "kv_tokens", "kv_gib", "max_concurrency", "load_sec"}.
    """
    cmd = (f"{VLLM_ENV}/bin/vllm serve {model} --served-model-name llm --port {port} "
           f"--max-model-len {max_model_len} --gpu-memory-utilization {gpu_mem} "
           f"--kv-cache-dtype {kv_cache_dtype} --enable-prefix-caching {extra}")
    sec = _start_server(cmd, port, timeout, f"chat, kv_cache_dtype={kv_cache_dtype}")
    info = kv_info(port)
    info.update({"kv_cache_dtype": kv_cache_dtype, "load_sec": sec})
    print(f"vLLM up in {sec}s | model={model} | kv_cache_dtype={kv_cache_dtype} | "
          f"KV cache = {info.get('kv_tokens')} tokens ({info.get('kv_gib')} GiB) | "
          f"max concurrency at {max_model_len} tokens = {info.get('max_concurrency')}x")
    return info


def start_embedder(model: str = "BAAI/bge-base-en-v1.5", port: int = 8001, gpu_mem: float = 0.10,
                   timeout: int = 900) -> int:
    """Start a second vLLM server that serves embeddings (OpenAI /v1/embeddings, model name "emb")."""
    cmd = (f"{VLLM_ENV}/bin/vllm serve {model} --served-model-name emb --port {port} "
           f"--runner pooling --gpu-memory-utilization {gpu_mem} --max-model-len 512")
    sec = _start_server(cmd, port, timeout, "embeddings")
    print(f"embedding server up in {sec}s | model={model} | port {port}")
    return sec


def embed(texts: list, port: int = 8001, batch: int = 64):
    """Embed texts with the embedding server; returns a normalized float32 numpy matrix."""
    import numpy as np
    import requests
    out = []
    for i in range(0, len(texts), batch):
        r = requests.post(f"http://localhost:{port}/v1/embeddings", timeout=300,
                          json={"model": "emb", "input": list(texts[i:i + batch]),
                                "truncate_prompt_tokens": 510})   # bge-base reads 512 word-pieces
        r.raise_for_status()
        out += [d["embedding"] for d in sorted(r.json()["data"], key=lambda d: d["index"])]
    E = np.asarray(out, dtype="float32")
    return E / np.linalg.norm(E, axis=1, keepdims=True)


def kv_info(port: int = VLLM_PORT) -> dict:
    """Parse the KV-cache capacity lines out of the vLLM log."""
    lp = Path(_log_path(port))
    txt = lp.read_text() if lp.exists() else ""
    tok = re.findall(r"KV cache size:\s*([\d,]+)\s*tokens", txt)
    conc = re.findall(r"Maximum concurrency for [\d,]+ tokens per request:\s*([\d.]+)x", txt)
    mem = re.findall(r"Available KV cache memory:\s*([\d.]+)\s*GiB", txt)
    return {"kv_tokens": int(tok[-1].replace(",", "")) if tok else None,
            "max_concurrency": float(conc[-1]) if conc else None,
            "kv_gib": float(mem[-1]) if mem else None}


def server_up(port: int = VLLM_PORT) -> bool:
    """True if an OpenAI-compatible server already answers on this port (e.g. after a kernel restart)."""
    import requests
    try:
        return requests.get(f"http://localhost:{port}/v1/models", timeout=2).ok
    except Exception:
        return False


def stop_vllm(port: int = VLLM_PORT):
    """Stop the vLLM server on one port (the chat server by default)."""
    import signal
    proc = _PROCS.pop(port, None)
    if proc is not None and proc.poll() is None:
        try:
            os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
            proc.wait(60)
        except Exception:
            try:
                os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
            except Exception:
                pass
    subprocess.run(f"pkill -f 'vllm serve.*--port {port}( |$)' || true", shell=True)
    time.sleep(3)


def llm(prompt: str | list, system: str | None = None, max_tokens: int = 400,
        temperature: float = 0.0) -> str:
    """Ask the local model one question (OpenAI chat API on localhost:8000)."""
    import requests
    msgs = prompt if isinstance(prompt, list) else (
        ([{"role": "system", "content": system}] if system else []) +
        [{"role": "user", "content": prompt}])
    r = requests.post(f"http://localhost:{VLLM_PORT}/v1/chat/completions", timeout=600,
                      json={"model": "llm", "messages": msgs, "max_tokens": max_tokens,
                            "temperature": temperature})
    r.raise_for_status()
    return r.json()["choices"][0]["message"]["content"]


def count_tokens(text: str, model: str = DEFAULT_MODEL) -> int:
    """Exact token count with the served model's tokenizer."""
    from transformers import AutoTokenizer
    return len(AutoTokenizer.from_pretrained(model).encode(text))


def gpu():
    """One-line GPU check."""
    try:
        out = subprocess.run("nvidia-smi --query-gpu=name,memory.total,memory.used "
                             "--format=csv,noheader", shell=True, capture_output=True, text=True)
        print(out.stdout.strip() or "no NVIDIA GPU visible")
    except Exception as e:  # pragma: no cover
        print("nvidia-smi failed:", e)


# ============================================================== async helper (Jupyter)

def run_async(coro):
    """Run a coroutine to completion from a notebook cell (which already has an event loop)."""
    import asyncio
    import threading
    box = {}

    def _runner():
        try:
            box["result"] = asyncio.run(coro)
        except BaseException as e:  # pragma: no cover
            box["error"] = e
    t = threading.Thread(target=_runner)
    t.start()
    t.join()
    if "error" in box:
        raise box["error"]
    return box.get("result")


# ======================================================================== GraphRAG (A5)

SECURITY_ENTITY_TYPES = ["organization", "person", "host", "account", "group", "software",
                         "vulnerability", "malware", "threat_actor", "ip_address", "domain",
                         "attack_technique", "incident", "network_segment"]
DEFAULT_ENTITY_TYPES = ["organization", "person", "geo", "event"]


def graphrag_project(root: str | Path, entity_types: list | None = None,
                     docs: Sequence[Document] | None = None, extra_files: Sequence[str] = ()) -> Path:
    """Create (or refresh) a Microsoft GraphRAG project folder wired to the local vLLM servers.

    root/input/          one .md per corpus document
    root/settings.yaml   from graphrag_settings.yaml with the entity types filled in
    root/prompts/        the default prompts written by `graphrag init`
    """
    root = Path(root)
    if not (root / "prompts").exists():
        subprocess.run(f"graphrag init --root {root} --force -m llm -e emb", shell=True, check=True,
                       capture_output=True)
    (root / "input").mkdir(parents=True, exist_ok=True)
    for d in (docs or load_corpus()):
        Path(root / "input" / Path(d.path).name).write_text(Path(d.path).read_text())
    for f in extra_files:
        Path(root / "input" / Path(f).name).write_text(Path(f).read_text())
    types = entity_types or SECURITY_ENTITY_TYPES
    tpl = (HERE / "graphrag_settings.yaml").read_text()
    (root / "settings.yaml").write_text(tpl.replace("{ENTITY_TYPES}", "[" + ",".join(types) + "]"))
    (root / ".env").write_text("GRAPHRAG_API_KEY=EMPTY\n")
    print(f"GraphRAG project ready at {root}: {len(list((root / 'input').glob('*.md')))} input files, "
          f"entity types = {types}")
    return root


def graphrag_index(root: str | Path, method: str = "standard") -> dict:
    """Run `graphrag index` (standard | fast) or `graphrag update` (standard-update | fast-update); time it."""
    root = Path(root)
    t = time.time()
    logf = root / f"index_{method}.log"
    with open(logf, "w") as fh:
        # GraphRAG 3.x: incremental updates are their own command, `graphrag update --method standard|fast`
        cmd = (f"graphrag update --root {root} --method {method[:-len('-update')]}" if method.endswith("-update")
               else f"graphrag index --root {root} --method {method}")
        p = subprocess.Popen(cmd, shell=True,
                             stdout=fh, stderr=subprocess.STDOUT, text=True)
        last = ""
        while p.poll() is None:            # show progress from GraphRAG's own log every 20 s
            time.sleep(20)
            eng = root / "logs" / "indexing-engine.log"
            if eng.exists():
                prog = [ln for ln in eng.read_text(errors="replace").splitlines() if "progress" in ln]
                if prog and prog[-1] != last:
                    last = prog[-1]
                    print(f"  [{time.time() - t:5.0f}s] {last.split(' - ')[-1][:100]}", flush=True)
    sec = round(time.time() - t, 1)
    tail = logf.read_text(errors="replace")[-2500:]
    if p.returncode != 0:
        print(tail)
        raise RuntimeError("graphrag index failed -- see the output above and root/logs/")
    stats = {}
    sp = root / "output" / "stats.json"
    if sp.exists():
        stats = json.loads(sp.read_text())
    print(f"{cmd.split(' --root')[0]} --method {method}: {sec} s")
    _GR_CACHE.pop(str(root), None)
    return {"seconds": sec, "stats": stats}


_GR_CACHE: dict = {}


def graphrag_tables(root: str | Path) -> dict:
    """The index as pandas DataFrames: entities, relationships, communities, community_reports, text_units."""
    import pandas as pd
    out = Path(root) / "output"
    names = ["entities", "relationships", "communities", "community_reports", "text_units", "documents"]
    return {n: pd.read_parquet(out / f"{n}.parquet") for n in names if (out / f"{n}.parquet").exists()}


def graphrag_ask(root: str | Path, method: str, question: str, community_level: int = 2,
                 response_type: str = "A short paragraph") -> str:
    """Ask the GraphRAG index a question. method: local | global | drift | basic."""
    import graphrag.api as api
    from graphrag.config.load_config import load_config
    key = str(root)
    if key not in _GR_CACHE:
        cfg = load_config(root_dir=Path(root))
        _GR_CACHE[key] = (cfg, graphrag_tables(root))
    cfg, T = _GR_CACHE[key]
    if method == "local":
        coro = api.local_search(config=cfg, entities=T["entities"], communities=T["communities"],
                                community_reports=T["community_reports"], text_units=T["text_units"],
                                relationships=T["relationships"], covariates=None,
                                community_level=community_level, response_type=response_type, query=question)
    elif method == "global":
        coro = api.global_search(config=cfg, entities=T["entities"], communities=T["communities"],
                                 community_reports=T["community_reports"], community_level=community_level,
                                 dynamic_community_selection=False, response_type=response_type, query=question)
    elif method == "drift":
        coro = api.drift_search(config=cfg, entities=T["entities"], communities=T["communities"],
                                community_reports=T["community_reports"], text_units=T["text_units"],
                                relationships=T["relationships"], community_level=community_level,
                                response_type=response_type, query=question)
    elif method == "basic":
        coro = api.basic_search(config=cfg, text_units=T["text_units"], response_type=response_type,
                                query=question)
    else:
        raise ValueError("method must be local, global, drift or basic")
    response, _context = run_async(coro)
    return response if isinstance(response, str) else json.dumps(response)[:2000]
